import org.jerkar.api.depmanagement.*;
import org.jerkar.api.java.JkJavaVersion;
import org.jerkar.tool.JkInit;
import org.jerkar.tool.JkOptions;
import org.jerkar.tool.builtins.java.JkJavaProjectBuild;

import java.nio.file.Paths;

/**
 * Jerkar build class (generated by Jerkar from existing pom).
 * 
 * @formatter:off
 */
class Build extends JkJavaProjectBuild {

    @Override
    protected void afterPluginsActivated() {
        project().setVersionedModule("org.jerkar.plugins:springboot", "2.0-SNAPSHOT");
        project().getCompileSpec().setSourceAndTargetVersion(JkJavaVersion.V8);
        project().addDependencies(JkDependencySet.of()
                .and(Paths.get("..\\..\\jerkar\\org.jerkar.core\\jerkar\\output\\distrib\\org.jerkar.core.jar"), JkJavaDepScopes.PROVIDED));
        project().setMavenPublicationInfo(mavenPublicationInfo());
    }

    protected JkMavenPublicationInfo mavenPublicationInfo() {
        return JkMavenPublicationInfo
                .of("Jerkar Add-in for Spring Boot", "A Jerkar add-in for Spring boot application", "http://jerkar.github.io")
                .withScm("https://github.com/jerkar/spring-boot-addin.git")
                .andApache2License()
                .andGitHubDeveloper("djeang", "djeangdev@yahoo.fr");
    }

    public static void main(String[] args) {
        JkInit.instanceOf(Build.class, args).maker().makeAllArtifacts();
    }

}